title: TÜBİTAK-120E534
logo: /assets/img/Sabanci_University_logo.png
description: Data Privacy Applications with Monte-Carlo Methods
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
