on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10p210 (2022-04-12 revision 67958) [x64-mingw32]
          bundler-cache: true
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
